import "../globals.css";
import type { Metadata } from "next";
import Header from "@/components/header";
import { Cairo } from "next/font/google";
import Navigation from "@/components/navigation";
import Loading from "./loading";
import { Suspense } from "react";

const roboto: any = Cairo({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <Header />
        <div className="flex-1 flex w-[90vw] py-5 max-w-5xl mx-auto">
          <Navigation />
          <Suspense fallback={<Loading />} >
          <div className="flex-1 flex flex-col ml-5 py-3 ">{children}</div>
          </Suspense>
        </div>
    </>
  );
}
